using System.Text.Json;
using Godot;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Nodes;
using MegaCrit.Sts2.Core.Nodes.Combat;
using MegaCrit.Sts2.Core.Nodes.GodotExtensions;
using TheArchitect.TheArchitectCode.Monsters;
using TheArchitect.TheArchitectCode.UI;

namespace TheArchitect.TheArchitectCode.Playtest;

// THROWAWAY: compare three below-body HUD formations in disposable native runs only.
// The HTML gallery owns variant selection; no production placement defaults are changed.
internal static class CorruptedPartyLayoutPrototype
{
    private static readonly List<object> Captures = [];
    private readonly record struct Slot(float Center, float Top, float Width, float Height, float HudScale);

    internal static async Task Capture(NGame game, IReadOnlyList<Creature> enemies)
    {
        if (!NativeDemoSafety.Enabled)
            throw new InvalidOperationException("Layout prototypes require disposable native storage.");
        var nodes = enemies.Select(enemy => enemy.GetCreatureNode()!).ToArray();
        var panels = nodes.Select(node => node.GetNode<CorruptedPlayerTelegraph>("CorruptedPlayerTelegraph")).ToArray();
        var scales = nodes.Select(node => node.Visuals.Scale).ToArray();
        for (var index = 0; index < nodes.Length; index++)
        {
            panels[index].SetProcess(false);
            ((CorruptedPlayer)enemies[index].Monster!).Native!.Player.PlayerCombatState!.GainStars(7 + index);
        }
        await game.ToSignal(game.GetTree().CreateTimer(1), SceneTreeTimer.SignalName.Timeout);

        foreach (var variant in new[] { "A", "B", "C" })
        {
            var measured = new List<object>();
            for (var index = 0; index < nodes.Length; index++)
            {
                var node = nodes[index];
                var panel = panels[index];
                var slot = Formation(variant, nodes.Length, index);
                node.Visuals.Scale = scales[index];
                var bounds = node.Visuals.GetNode<Control>("%Bounds");
                var original = bounds.GetGlobalRect();
                var factor = Math.Min(slot.Height / original.Size.Y, (slot.Width - 90) / original.Size.X);
                node.Visuals.Scale = scales[index] * Math.Min(nodes.Length >= 3 ? 0.85f : 1f, factor);
                var body = bounds.GetGlobalRect();
                var top = variant == "B" ? slot.Top + slot.Height - body.Size.Y : slot.Top;
                node.GlobalPosition += new Vector2(slot.Center - body.GetCenter().X, top - body.Position.Y);
                body = bounds.GetGlobalRect();
                node.Hitbox.GlobalPosition = body.Position;
                node.Hitbox.Size = body.Size / node.GetGlobalTransform().Scale;
                node.GetNode<NCreatureStateDisplay>("%HealthBar").SetCreatureBounds(node.Hitbox);

                panel.Scale = Vector2.One * slot.HudScale / node.GetGlobalTransform().Scale;
                panel.CustomMinimumSize = new Vector2(slot.Width / slot.HudScale, 228);
                panel.Size = panel.CustomMinimumSize;
                panel.GlobalPosition = new Vector2(slot.Center - slot.Width / 2, body.End.Y + 40);
                panel.GetNode<ScrollContainer>("HandScroll").ScrollHorizontal = 0;
            }
            for (var frame = 0; frame < 4; frame++)
                await game.AwaitProcessFrame();
            for (var index = 0; index < nodes.Length; index++)
            {
                var node = nodes[index];
                var panel = panels[index];
                measured.Add(new
                {
                    actor = index + 1,
                    character = ((CorruptedPlayer)enemies[index].Monster!).Native!.Player.Character.Id.Entry,
                    stars = 7 + index,
                    bodyScale = node.Visuals.Scale.X / scales[index].X,
                    body = Rect(node.Visuals.GetNode<Control>("%Bounds").GetGlobalRect()),
                    hitbox = Rect(node.Hitbox.GetGlobalRect()),
                    hud = Rect(panel.GetGlobalRect()),
                    hudScale = panel.GetGlobalTransform().Scale.X,
                    handViewport = Rect(panel.GetNode<ScrollContainer>("HandScroll").GetGlobalRect())
                });
            }
            var image = $"party-{nodes.Length}-layout-{variant}.png";
            await NativeDemoPlaytest.Capture(Path.GetFileNameWithoutExtension(image));
            Captures.Add(new { variant, players = nodes.Length, image, actors = measured });
            File.WriteAllText(Path.Combine(NativeDemoSafety.RuntimePath, "layout-metadata.json"),
                JsonSerializer.Serialize(new
                {
                    prototype = true,
                    resolution = new { width = 1920, height = 1080 },
                    stars = "Fixture-granted, not naturally generated by cards.",
                    health = "Ordinary starting character HP; native party UI preserved.",
                    captures = Captures
                }, new JsonSerializerOptions { WriteIndented = true }));
        }
    }

    private static Slot Formation(string variant, int count, int index)
    {
        if (variant == "A")
        {
            if (count == 2)
                return new Slot(1090 + index * 540, 235, 445, 335, 0.65f);
            var column = index % 2;
            var row = index / 2;
            var center = count == 3 && index == 2 ? 1360 : 1090 + column * 540;
            return new Slot(center, 170 + row * 370, 420, 130, 0.6f);
        }
        if (variant == "B")
        {
            var width = 1080f / count;
            return new Slot(810 + width * (index + 0.5f), 290, width - 16,
                count == 2 ? 320 : 275, count == 2 ? 0.65f : 0.55f);
        }
        var cellWidth = 1080f / count;
        var top = count == 2 ? 200 + index * 160 : 250 + (index % 2) * 130 + index * 12;
        return new Slot(810 + cellWidth * (index + 0.5f), top, cellWidth - 16,
            count == 2 ? 280 : 205, count == 2 ? 0.65f : 0.55f);
    }

    private static object Rect(Rect2 rect) => new
    {
        x = rect.Position.X, y = rect.Position.Y, width = rect.Size.X, height = rect.Size.Y
    };
}
